---
- name: apache2
  hosts: node01
  become: true

  tasks: 
    - name: Install apache httpd  
      apt:
       name: apache2
       state: present

    - name: Copy index.html file in /var/www/html/
      copy:
       src: ~/workspace/Ansible/web/
       dest: /var/www/html
 
    - name: Start service apache
      service:
       name: apache2
       state: started

    - name: Enable service apache
      service:
       name: apache2
       enabled: yes
